{% set name = "localstack" %}
{% set version = "0.12.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a55ea43baac659c696bceb1f5d3ad288f6434733f557646db7ce3553795d7ef

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [python_impl == 'pypy']

requirements:
  host:
    - pip
    - python
  run:
    - boto3
    - docopt
    - localstack-client
    - localstack-ext
    - python
    - six

test:
  imports:
    - localstack
    - localstack.dashboard
    - localstack.services
    - localstack.services.apigateway
    - localstack.services.awslambda
    - localstack.services.cloudformation
    - localstack.services.dynamodb
    - localstack.services.dynamodbstreams
    - localstack.services.es
    - localstack.services.firehose
    - localstack.services.iam
    - localstack.services.kinesis
    - localstack.services.s3
    - localstack.services.sns
    - localstack.services.sqs
    - localstack.services.stepfunctions
    - localstack.stepfunctions
    - localstack.utils
    - localstack.utils.analytics
    - localstack.utils.aws
    - localstack.utils.cloudformation
    - localstack.utils.cloudwatch
    - localstack.utils.kinesis
    - localstack.utils.server

about:
  home: https://github.com/localstack/localstack
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: An easy-to-use test/mocking framework for developing Cloud applications
  doc_url: https://pypi.org/project/localstack/
  dev_url: https://github.com/localstack/localstack

extra:
  recipe-maintainers:
    - mwilson8
    - oblute
    - rluria14
